# -*- coding: utf-8 -*-
"""base-line-model-pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdgN3ZF79UWc7fz60mtFQ4VU_yu9o8Fs
"""

from src.fine_tuned_finbert.datasets.data_modules.semeval_2017_test import Semeval2017Test
from src.baseline_model_TODO.model.base_line_but_still_sauced import BLBSSModel
from torch.utils.data.dataloader import DataLoader
import torch.nn as nn
import torch
import numpy as np
import pandas as pd
from src.utils.io import PROJECT_ROOT

"""Fetch the dataloader from `semeval_2017_test` and instantiate the baseline model"""

data_handler = Semeval2017Test()
data_loader: DataLoader = data_handler.test_dataloader()

bl_model: BLBSSModel = BLBSSModel()

def predict(model: nn.Module, data_loader: DataLoader, path: str) -> None:
    predictions: np.ndarray[float] = np.array([], dtype=np.float_)
    model.eval()

    with torch.no_grad():
        for batch in data_loader:
            batch_pred: np.ndarray[float] = model(batch).cpu().numpy()
            predictions = np.concatenate((predictions, batch_pred))


    df: pd.DataFrame = pd.DataFrame(predictions)
    df.to_csv(path, index=False)

path = PROJECT_ROOT / "data" / "evaluation" / "base_mode_pred.csv"

predict(model=bl_model, data_loader=data_loader, path=path)