import enum


class Dataset(enum.StrEnum):
    SC_TRAIN_VAL = 'SC_TRAIN_VAL'
    SC_TRAIN_SEMEVAL_VAL = 'SC_TRAIN_SEMEVAL_VAL'
    SEMEVAL_TRAIN = 'SEMEVAL_TRAIN'
    SEMEVAL_TRAIN_VAL = 'SEMEVAL_TRAIN_VAL'
    SEMEVAL_TEST = 'SEMEVAL_TEST'


class Model(enum.StrEnum):
    FINBERT = 'FINBERT'
    HAND_ENG_MLP = 'HAND_ENG_MLP'
    END_TO_END = 'END_TO_END'
